const COLOR = {
  PRIMARY_ORANGE: '#FE8C46',
  PRIMARY_ORANGE2: '#FFEEE3',
  PRIMARY_WHITE: '#FFFFFF',
  PRIMARY_WHITE_85: '#ffffffd9',
  PRIMARY_BLACK: '#120000',
  PRIMARY_GRAY1: '#DFDFDF',
  PRIMARY_GRAY2: '#F3F2F2',
  BG_GRAY1: '#FBF9F6',
  BG_GRAY1_85: '#FBF9F6d9',
  TYPEFACE_GRAY1: '#7B7B7B',
  TYPEFACE_GRAY2: '#B3B3B3',
  TYPEFACE_BLACK: '#242424',
  TYPEFACE_WHITE: '#FFFFFF',
} as const;

export default COLOR;
